application: my-web-project-1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: webBlog.app

libraries:
- name: jinja2
  version: latest